version: 2
jobs:
 test:
  docker:
   - image: holochain/holonix
  steps:
   - checkout
   - run:
      name: rust tests
      command: nix-shell --run 'cargo test'

workflows:
 version: 2
 build:
  jobs:
   - test
